spring.application.name=sb-ecom
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB

imgbb.api.key=${IMGBB_API_KEY}
imgbb.api.url=https://api.imgbb.com/1/upload

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.cookie=${JWT_COOKIE_NAME:springBootECommerce}
jwt.cookie.secure=${JWT_COOKIE_SECURE:false}
jwt.cookie.http-only=${JWT_COOKIE_HTTP_ONLY:false}
jwt.cookie.same-site=${JWT_COOKIE_SAME_SITE:Lax}

frontend.url=${FRONTEND_URL:http://localhost:5173}

stripe.api.key=${STRIPE_API_KEY}






#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG

